### ISSUE TITLE
[improvement] Documentation is not enough to setup trhough *.deb

### ISSUE THREAD

**Issue by WatchTh1** [schorschii/companion-linux#1]
After installing DEB-package trying to edit file causes message^
 "You need to trust Companion application to edit files".

Confluence site is set up in /usr/bin/companion.py as
ALLOWED_SITE = "https://site.name.com"

Socondly I'd like to add several sites to allowed ones, how can i make it happen?

**Comment by schorschii** [comment]
- Please enter only the name of your Confluence installation in ALLOWED_SITE, not the whole URL. You see the name of your Confluence installation in the upper left corner on the web page. A GUI dialog for trusting sites is planned for future versions, which should improve the user experience.
- Trusting multiple sites is not implemented in current version.

**Comment by WatchTh1** [comment]
Will it be enough to change 
https://github.com/schorschii/companion-linux/blob/eae3f129d0dadd4b58b1cf502d3f4d20e70b702b/companion.py#L28
and 
https://github.com/schorschii/companion-linux/blob/eae3f129d0dadd4b58b1cf502d3f4d20e70b702b/companion.py#L40
adding an array of names instead of single string ?

**Comment by schorschii** [comment]
Please have a look at v0.3 which introduces multiple site support and a GUI dialog for trusting new sites.
