### ISSUE TITLE
Infinite loader on Linux Mint 19.3 Cinnamon

### ISSUE THREAD

**Issue by denis-colliot** [schorschii/companion-linux#3]
## Tested version

- Companion version: 0.3-2 (installed with `.deb` package)
- Confluence version: 1000.0.0-04939a47e6a9 (cloud version: `<mycompany>.atlassian.net`)

## System details

- OS : Linux Mint 19.3 Cinnamon
- Cinnamon version : 4.4.8
- Linux Kernel : 5.3.0-42-generic
- Browsers (both fail) : Chrome 80.0.3987.149 (Official Build) (64-bit) + Firefox 74.0 (64-bit)

## Behaviour

Edit popup opens and its inner loader starts rolling indefinitely:

![Screenshot from 2020-03-30 15-29-14](https://user-images.githubusercontent.com/7382968/77920110-52562d00-729e-11ea-80cd-33c3bd094db4.png)

**Comment by schorschii** [comment]
Can you please start companion.py in terminal and post the output here?
```
killall companion.py 
companion.py
# Please click on "Edit with" now. This should produce some output in the terminal.
```
Which version of Confluence are you using?

**Comment by denis-colliot** [comment]
I got the following result just by viewing the file on confluence (I didn't even click on "Edit with"):

```
$ killall companion.py
$ companion.py
< {"type":"authentication","payload":{"provider":"jwt","payload":"<PAYLOAD>"},"requestID":1}
Error in connection handler
Traceback (most recent call last):
  File "/home/denis/.local/lib/python3.6/site-packages/websockets/server.py", line 191, in handler
    await self.ws_handler(self, path)
  File "/usr/bin/companion.py", line 265, in companionHandler
    await handleJson( websocket, json.loads(request) )
  File "/usr/bin/companion.py", line 64, in handleJson
    currentSiteTitle = requestjson["payload"]["payload"]["siteTitle"]
TypeError: string indices must be integers
```

**Comment by denis-colliot** [comment]
And I am using Confluence 1000.0.0-04939a47e6a9

**Comment by schorschii** [comment]
Hmm, the first line does not look like the requests from Confluence I discovered. My script expects something like this:
```
{"type":"authentication","payload":{"provider":"server","payload":{"siteTitle":"Übersicht"}},"requestID":1}
```
Your output says:
```
... "provider":"jwt" ...
```
Is there maybe something else running on your machine which connects to port 31459?

Are you using some kind of dev/beta version? At the bottom of my Confluence I see something like "Powered by Atlassian Confluence 6.15.9". Maybe Atlassian has changed something in a newer version. I'll take a closer look at that.

**Comment by denis-colliot** [comment]
Well, [JWT](https://jwt.io/) is a common authentication mechanism, it's not a really a surprise to see that Confluence is using it.

And, no such footer on my Confluence pages, I found the version through the "Help" menu on the sidebar:

![Screenshot from 2020-03-30 18-26-43](https://user-images.githubusercontent.com/7382968/77937049-0dd58c00-72b4-11ea-8e58-a020a0eb42e8.png)

**Comment by schorschii** [comment]
Yes, it's not a surprise, but I never discovered it before in Companion context.

I haven't tested it yet with a cloud version of confluence. I'll take a closer look at that.

**Comment by schorschii** [comment]
Can you please test the companion script from the current master branch?

**Comment by schorschii** [comment]
@denis-colliot 
Where are u?

**Comment by denis-colliot** [comment]
Well I have quite a lot of work to do and testing your code is not on my top priorities list right now ;-)

But, as soon as I have a few moments, I'll give it another try and I'll come back to you.

**Comment by denis-colliot** [comment]
Just so you know, I tried with your latest master version (`c45b8fe`) and it worked! \o/

Well I had to accept a system popup asking me if I trusted "atlassian.com" and then magic appeared:
![Screenshot from 2020-04-07 19-16-43](https://user-images.githubusercontent.com/7382968/78699669-8e276d00-7904-11ea-8e1c-03ef9acc872c.png)

Unfortunately, the confluence solution isn't well adapted for my company's problem so I no longer need your script, but keep on the good work!

**Comment by schorschii** [comment]
Thanks for your feedback!
