### ISSUE TITLE
[Bug] Site name containing cyrrilic symbols is not recognized.

### ISSUE THREAD

**Issue by WatchTh1** [schorschii/companion-linux#4]
**Tested Version**
- Companion script version: 0/4
- Installed via .deb package? (yes):

**System Details**
- Confluence version: 6.15.4, Site name sstring: "База знаний - 1"
- Operating System: Ubuntu 20.04 LTS
- Browser: Google Chrome

**Bug Description**
Companion doesn't recognize site contaning cyrillic symbols after restart.
**Preconditions**
Site has not to be in allowed sites list.

**Behaviour**
1. Go to page containing attachement on site.
2. Click on button "Edit" (anyway)
3. Add site to allowed sites list.
4. Edit attachement.
5, End user session or reboot.
6. Login and go to page containing attachement on site again.
7. Click on button "Edit" (anyway)
8. Companion tells to "trust" this site.

**Workaround**
After each session delete a file: $HOME/.config/allowed

**Additional Info**
File $HOME/.config/allowed contains incorrect cyrrilic symbols like:
�� when correct spelling should be ТН (cyr)

**Comment by WatchTh1** [comment]
I suggest to use json-based config files instead of using pickle.
Encding problems should be negated by using utf8-encoded strings.

**Comment by WatchTh1** [comment]
Moreover I've noticed following confluence behaviour when processing requests:

```
{'type': 'authentication', 'payload': {'provider': 'server', 'payload': {}}, 'requestID': 1}
{'type': 'authentication', 'payload': {'provider': 'server', 'payload': {}}, 'requestID': 1}
```

**Comment by schorschii** [comment]
I can reproduce your server response with missing `siteTitle` in Confluence 6.15.4.
```
{'type': 'authentication', 'payload': {'provider': 'server', 'payload': {}}, 'requestID': 1}
```
This is the reason for the problem. There is no specific problem with cyrillic symbols. Please update your confluence to version 6.15.10, which sends the `siteTitle` in the server response.

With 6.15.10 everything works fine, even with cyrillic characters in the site title.
